// This file is automatically generated by Firebase Studio.
//
// To change the Firebase project, use the "Change Firebase Project" command
// or edit this file and then call the "Update Firebase Project" command.
export const firebaseConfig = {
  apiKey: "AIzaSyAsMH__pN912k0rlVu48apRykJXqPb9m88",
  authDomain: "studio-6846243418-deb19.firebaseapp.com",
  projectId: "studio-6846243418-deb19",
  storageBucket: "studio-6846243418-deb19.firebasestorage.app",
  messagingSenderId: "371779115722",
  appId: "1:371779115722:web:4d241a892a277c59c8f233"
};
